// This file is auto-generated by @hey-api/openapi-ts

export type InvoiceHeader = {
    id: number;
    customerName: string;
    customerAddress: string;
    items?: Array<InvoiceLine> | null;
};

export type InvoiceLine = {
    invoiceId: number;
    lineNumber: number;
    itemNumber: string;
    description?: string | null;
    unitPrice: number;
    quantity: number;
};

export type InvoiceLineMutationReadable = {
    itemNumber: string;
    description?: string | null;
    unitPrice: number;
    quantity: number;
    readonly totalPrice: number;
};

export type InvoiceLineMutationWritable = {
    itemNumber: string;
    description?: string | null;
    unitPrice: number;
    quantity: number;
};

export type InvoiceMutation = {
    customerName: string;
    customerAddress: string;
};

export type DeleteInvoiceByInvoiceIdData = {
    body?: never;
    path: {
        invoiceId: number;
    };
    query?: never;
    url: '/Invoice/{invoiceId}';
};

export type DeleteInvoiceByInvoiceIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetInvoiceByInvoiceIdData = {
    body?: never;
    path: {
        invoiceId: number;
    };
    query?: never;
    url: '/Invoice/{invoiceId}';
};

export type GetInvoiceByInvoiceIdResponses = {
    /**
     * OK
     */
    200: InvoiceHeader;
};

export type GetInvoiceByInvoiceIdResponse = GetInvoiceByInvoiceIdResponses[keyof GetInvoiceByInvoiceIdResponses];

export type PutInvoiceByInvoiceIdData = {
    body?: InvoiceMutation;
    path: {
        invoiceId: number;
    };
    query?: never;
    url: '/Invoice/{invoiceId}';
};

export type PutInvoiceByInvoiceIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetInvoiceListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/Invoice/List';
};

export type GetInvoiceListResponses = {
    /**
     * OK
     */
    200: Array<InvoiceHeader>;
};

export type GetInvoiceListResponse = GetInvoiceListResponses[keyof GetInvoiceListResponses];

export type PostInvoiceData = {
    body?: InvoiceMutation;
    path?: never;
    query?: never;
    url: '/Invoice';
};

export type PostInvoiceResponses = {
    /**
     * OK
     */
    200: number;
};

export type PostInvoiceResponse = PostInvoiceResponses[keyof PostInvoiceResponses];

export type DeleteInvoiceLineByInvoiceIdByLineNumberData = {
    body?: never;
    path: {
        invoiceId: number;
        lineNumber: number;
    };
    query?: never;
    url: '/Invoice/Line/{invoiceId}/{lineNumber}';
};

export type DeleteInvoiceLineByInvoiceIdByLineNumberResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetInvoiceLineByInvoiceIdByLineNumberData = {
    body?: never;
    path: {
        invoiceId: number;
        lineNumber: number;
    };
    query?: never;
    url: '/Invoice/Line/{invoiceId}/{lineNumber}';
};

export type GetInvoiceLineByInvoiceIdByLineNumberResponses = {
    /**
     * OK
     */
    200: InvoiceLine;
};

export type GetInvoiceLineByInvoiceIdByLineNumberResponse = GetInvoiceLineByInvoiceIdByLineNumberResponses[keyof GetInvoiceLineByInvoiceIdByLineNumberResponses];

export type PutInvoiceLineByInvoiceIdByLineNumberData = {
    body?: InvoiceLineMutationWritable;
    path: {
        invoiceId: number;
        lineNumber: number;
    };
    query?: never;
    url: '/Invoice/Line/{invoiceId}/{lineNumber}';
};

export type PutInvoiceLineByInvoiceIdByLineNumberResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostInvoiceLineByInvoiceIdData = {
    body?: InvoiceLineMutationWritable;
    path: {
        invoiceId: number;
    };
    query?: never;
    url: '/Invoice/Line/{invoiceId}';
};

export type PostInvoiceLineByInvoiceIdResponses = {
    /**
     * OK
     */
    200: number;
};

export type PostInvoiceLineByInvoiceIdResponse = PostInvoiceLineByInvoiceIdResponses[keyof PostInvoiceLineByInvoiceIdResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:7153' | (string & {});
};